// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: sandbox.proto

package sandboxpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Command       string                 `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	Args          []string               `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty"`
	Env           map[string]string      `protobuf:"bytes,5,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	WorkDir       string                 `protobuf:"bytes,6,opt,name=work_dir,json=workDir,proto3" json:"work_dir,omitempty"`
	TimeoutSec    uint32                 `protobuf:"varint,7,opt,name=timeout_sec,json=timeoutSec,proto3" json:"timeout_sec,omitempty"`
	Limits        *ResourceLimits        `protobuf:"bytes,8,opt,name=limits,proto3" json:"limits,omitempty"`
	InputFiles    map[string][]byte      `protobuf:"bytes,9,rep,name=input_files,json=inputFiles,proto3" json:"input_files,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Stdin         []byte                 `protobuf:"bytes,10,opt,name=stdin,proto3" json:"stdin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_sandbox_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ExecuteRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ExecuteRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ExecuteRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ExecuteRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ExecuteRequest) GetWorkDir() string {
	if x != nil {
		return x.WorkDir
	}
	return ""
}

func (x *ExecuteRequest) GetTimeoutSec() uint32 {
	if x != nil {
		return x.TimeoutSec
	}
	return 0
}

func (x *ExecuteRequest) GetLimits() *ResourceLimits {
	if x != nil {
		return x.Limits
	}
	return nil
}

func (x *ExecuteRequest) GetInputFiles() map[string][]byte {
	if x != nil {
		return x.InputFiles
	}
	return nil
}

func (x *ExecuteRequest) GetStdin() []byte {
	if x != nil {
		return x.Stdin
	}
	return nil
}

type ResourceLimits struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemoryBytes   uint64                 `protobuf:"varint,1,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	CpuShares     uint64                 `protobuf:"varint,2,opt,name=cpu_shares,json=cpuShares,proto3" json:"cpu_shares,omitempty"`
	DiskBytes     uint64                 `protobuf:"varint,3,opt,name=disk_bytes,json=diskBytes,proto3" json:"disk_bytes,omitempty"`
	MaxPids       uint32                 `protobuf:"varint,4,opt,name=max_pids,json=maxPids,proto3" json:"max_pids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceLimits) Reset() {
	*x = ResourceLimits{}
	mi := &file_sandbox_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceLimits) ProtoMessage() {}

func (x *ResourceLimits) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceLimits.ProtoReflect.Descriptor instead.
func (*ResourceLimits) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{1}
}

func (x *ResourceLimits) GetMemoryBytes() uint64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *ResourceLimits) GetCpuShares() uint64 {
	if x != nil {
		return x.CpuShares
	}
	return 0
}

func (x *ResourceLimits) GetDiskBytes() uint64 {
	if x != nil {
		return x.DiskBytes
	}
	return 0
}

func (x *ResourceLimits) GetMaxPids() uint32 {
	if x != nil {
		return x.MaxPids
	}
	return 0
}

type ExecuteResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout        []byte                 `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        []byte                 `protobuf:"bytes,3,opt,name=stderr,proto3" json:"stderr,omitempty"`
	TimedOut      bool                   `protobuf:"varint,4,opt,name=timed_out,json=timedOut,proto3" json:"timed_out,omitempty"`
	ResourceUsage *ResourceUsage         `protobuf:"bytes,5,opt,name=resource_usage,json=resourceUsage,proto3" json:"resource_usage,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResult) Reset() {
	*x = ExecuteResult{}
	mi := &file_sandbox_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResult) ProtoMessage() {}

func (x *ExecuteResult) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResult.ProtoReflect.Descriptor instead.
func (*ExecuteResult) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{2}
}

func (x *ExecuteResult) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecuteResult) GetStdout() []byte {
	if x != nil {
		return x.Stdout
	}
	return nil
}

func (x *ExecuteResult) GetStderr() []byte {
	if x != nil {
		return x.Stderr
	}
	return nil
}

func (x *ExecuteResult) GetTimedOut() bool {
	if x != nil {
		return x.TimedOut
	}
	return false
}

func (x *ExecuteResult) GetResourceUsage() *ResourceUsage {
	if x != nil {
		return x.ResourceUsage
	}
	return nil
}

func (x *ExecuteResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ResourceUsage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MemoryPeakBytes uint64                 `protobuf:"varint,1,opt,name=memory_peak_bytes,json=memoryPeakBytes,proto3" json:"memory_peak_bytes,omitempty"`
	CpuTimeUsec     uint64                 `protobuf:"varint,2,opt,name=cpu_time_usec,json=cpuTimeUsec,proto3" json:"cpu_time_usec,omitempty"`
	UserTimeUsec    uint64                 `protobuf:"varint,3,opt,name=user_time_usec,json=userTimeUsec,proto3" json:"user_time_usec,omitempty"`
	SystemTimeUsec  uint64                 `protobuf:"varint,4,opt,name=system_time_usec,json=systemTimeUsec,proto3" json:"system_time_usec,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ResourceUsage) Reset() {
	*x = ResourceUsage{}
	mi := &file_sandbox_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceUsage) ProtoMessage() {}

func (x *ResourceUsage) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceUsage.ProtoReflect.Descriptor instead.
func (*ResourceUsage) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{3}
}

func (x *ResourceUsage) GetMemoryPeakBytes() uint64 {
	if x != nil {
		return x.MemoryPeakBytes
	}
	return 0
}

func (x *ResourceUsage) GetCpuTimeUsec() uint64 {
	if x != nil {
		return x.CpuTimeUsec
	}
	return 0
}

func (x *ResourceUsage) GetUserTimeUsec() uint64 {
	if x != nil {
		return x.UserTimeUsec
	}
	return 0
}

func (x *ResourceUsage) GetSystemTimeUsec() uint64 {
	if x != nil {
		return x.SystemTimeUsec
	}
	return 0
}

var File_sandbox_proto protoreflect.FileDescriptor

const file_sandbox_proto_rawDesc = "" +
	"\n" +
	"\rsandbox.proto\x12\asandbox\"\xe8\x03\n" +
	"\x0eExecuteRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x04 \x03(\tR\x04args\x122\n" +
	"\x03env\x18\x05 \x03(\v2 .sandbox.ExecuteRequest.EnvEntryR\x03env\x12\x19\n" +
	"\bwork_dir\x18\x06 \x01(\tR\aworkDir\x12\x1f\n" +
	"\vtimeout_sec\x18\a \x01(\rR\n" +
	"timeoutSec\x12/\n" +
	"\x06limits\x18\b \x01(\v2\x17.sandbox.ResourceLimitsR\x06limits\x12H\n" +
	"\vinput_files\x18\t \x03(\v2'.sandbox.ExecuteRequest.InputFilesEntryR\n" +
	"inputFiles\x12\x14\n" +
	"\x05stdin\x18\n" +
	" \x01(\fR\x05stdin\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a=\n" +
	"\x0fInputFilesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\x8c\x01\n" +
	"\x0eResourceLimits\x12!\n" +
	"\fmemory_bytes\x18\x01 \x01(\x04R\vmemoryBytes\x12\x1d\n" +
	"\n" +
	"cpu_shares\x18\x02 \x01(\x04R\tcpuShares\x12\x1d\n" +
	"\n" +
	"disk_bytes\x18\x03 \x01(\x04R\tdiskBytes\x12\x19\n" +
	"\bmax_pids\x18\x04 \x01(\rR\amaxPids\"\xce\x01\n" +
	"\rExecuteResult\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x02 \x01(\fR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x03 \x01(\fR\x06stderr\x12\x1b\n" +
	"\ttimed_out\x18\x04 \x01(\bR\btimedOut\x12=\n" +
	"\x0eresource_usage\x18\x05 \x01(\v2\x16.sandbox.ResourceUsageR\rresourceUsage\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"\xaf\x01\n" +
	"\rResourceUsage\x12*\n" +
	"\x11memory_peak_bytes\x18\x01 \x01(\x04R\x0fmemoryPeakBytes\x12\"\n" +
	"\rcpu_time_usec\x18\x02 \x01(\x04R\vcpuTimeUsec\x12$\n" +
	"\x0euser_time_usec\x18\x03 \x01(\x04R\fuserTimeUsec\x12(\n" +
	"\x10system_time_usec\x18\x04 \x01(\x04R\x0esystemTimeUsec2L\n" +
	"\x0eSandboxService\x12:\n" +
	"\aExecute\x12\x17.sandbox.ExecuteRequest\x1a\x16.sandbox.ExecuteResultBEZCgithub.com/tangying-ai/aios-core/internal/core/worker/executor/sandboxpbb\x06proto3"

var (
	file_sandbox_proto_rawDescOnce sync.Once
	file_sandbox_proto_rawDescData []byte
)

func file_sandbox_proto_rawDescGZIP() []byte {
	file_sandbox_proto_rawDescOnce.Do(func() {
		file_sandbox_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sandbox_proto_rawDesc), len(file_sandbox_proto_rawDesc)))
	})
	return file_sandbox_proto_rawDescData
}

var file_sandbox_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_sandbox_proto_goTypes = []any{
	(*ExecuteRequest)(nil), // 0: sandbox.ExecuteRequest
	(*ResourceLimits)(nil), // 1: sandbox.ResourceLimits
	(*ExecuteResult)(nil),  // 2: sandbox.ExecuteResult
	(*ResourceUsage)(nil),  // 3: sandbox.ResourceUsage
	nil,                    // 4: sandbox.ExecuteRequest.EnvEntry
	nil,                    // 5: sandbox.ExecuteRequest.InputFilesEntry
}
var file_sandbox_proto_depIdxs = []int32{
	4, // 0: sandbox.ExecuteRequest.env:type_name -> sandbox.ExecuteRequest.EnvEntry
	1, // 1: sandbox.ExecuteRequest.limits:type_name -> sandbox.ResourceLimits
	5, // 2: sandbox.ExecuteRequest.input_files:type_name -> sandbox.ExecuteRequest.InputFilesEntry
	3, // 3: sandbox.ExecuteResult.resource_usage:type_name -> sandbox.ResourceUsage
	0, // 4: sandbox.SandboxService.Execute:input_type -> sandbox.ExecuteRequest
	2, // 5: sandbox.SandboxService.Execute:output_type -> sandbox.ExecuteResult
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_sandbox_proto_init() }
func file_sandbox_proto_init() {
	if File_sandbox_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sandbox_proto_rawDesc), len(file_sandbox_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sandbox_proto_goTypes,
		DependencyIndexes: file_sandbox_proto_depIdxs,
		MessageInfos:      file_sandbox_proto_msgTypes,
	}.Build()
	File_sandbox_proto = out.File
	file_sandbox_proto_goTypes = nil
	file_sandbox_proto_depIdxs = nil
}
