#!/usr/bin/env bash

set -euo pipefail

usage() {
  cat <<'EOF'
Usage: scripts/workspace-archive.sh <archive|list|restore> [options]

Options:
  --root PATH          Workspace root. Defaults to the current Git worktree.
  --archive-root PATH  Archive directory. Defaults to ROOT/.workspace-archive.
  --label NAME         Snapshot label. Required by restore; generated by archive.
  --dry-run            Print moves without changing the workspace.
  --include-build      Also archive local frontend/backend build products.
  --target PATH        Archive a custom root-relative path; may be repeated.
  -h, --help           Show this help.
EOF
}

command_name="${1:-archive}"
if [[ "$command_name" == "archive" || "$command_name" == "list" || "$command_name" == "restore" ]]; then
  shift || true
else
  echo "ERROR: unknown command '$command_name'." >&2
  usage >&2
  exit 2
fi

workspace_root=""
archive_root=""
label=""
dry_run="false"
include_build="false"
custom_targets=()

while [[ $# -gt 0 ]]; do
  case "$1" in
    --root)
      workspace_root="${2:-}"
      shift 2
      ;;
    --archive-root)
      archive_root="${2:-}"
      shift 2
      ;;
    --label)
      label="${2:-}"
      shift 2
      ;;
    --dry-run)
      dry_run="true"
      shift
      ;;
    --include-build)
      include_build="true"
      shift
      ;;
    --target)
      custom_targets+=("${2:-}")
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "ERROR: unknown option '$1'." >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ -z "$workspace_root" ]]; then
  workspace_root="$(git rev-parse --show-toplevel)"
fi
workspace_root="$(cd "$workspace_root" && pwd -P)"

if [[ -z "$archive_root" ]]; then
  archive_root="$workspace_root/.workspace-archive"
fi
mkdir -p "$(dirname "$archive_root")"
archive_parent="$(cd "$(dirname "$archive_root")" && pwd -P)"
archive_root="$archive_parent/$(basename "$archive_root")"

case "$archive_root/" in
  "$workspace_root/"*) ;;
  *)
    echo "ERROR: archive root must stay inside the workspace: $archive_root" >&2
    exit 2
    ;;
esac
if [[ "$archive_root" == "$workspace_root" ]]; then
  echo "ERROR: archive root cannot equal the workspace root." >&2
  exit 2
fi

if [[ "$command_name" == "list" ]]; then
  if [[ ! -d "$archive_root" ]]; then
    echo "No workspace archives."
    exit 0
  fi
  find "$archive_root" -mindepth 1 -maxdepth 1 -type d -print | sort
  exit 0
fi

if [[ -z "$label" ]]; then
  if [[ "$command_name" == "restore" ]]; then
    echo "ERROR: restore requires --label." >&2
    exit 2
  fi
  label="$(date '+%Y%m%d-%H%M%S')"
fi
if [[ ! "$label" =~ ^[A-Za-z0-9._-]+$ ]]; then
  echo "ERROR: label may contain only letters, numbers, dot, underscore, and hyphen." >&2
  exit 2
fi

snapshot="$archive_root/$label"
manifest="$snapshot/manifest.tsv"

if [[ "$command_name" == "restore" ]]; then
  if [[ ! -f "$manifest" ]]; then
    echo "ERROR: archive manifest not found: $manifest" >&2
    exit 2
  fi
  while IFS=$'\t' read -r source archived size_kib; do
    [[ "$source" == "source" ]] && continue
    source_path="$workspace_root/$source"
    archived_path="$snapshot/$archived"
    if [[ -e "$source_path" ]]; then
      echo "ERROR: restore target already exists: $source_path" >&2
      exit 1
    fi
    if [[ ! -e "$archived_path" ]]; then
      echo "ERROR: archived payload is missing: $archived_path" >&2
      exit 1
    fi
    echo "RESTORE $source (${size_kib} KiB)"
    if [[ "$dry_run" == "false" ]]; then
      mkdir -p "$(dirname "$source_path")"
      mv "$archived_path" "$source_path"
    fi
  done < "$manifest"
  exit 0
fi

if [[ -e "$snapshot" ]]; then
  echo "ERROR: snapshot already exists: $snapshot" >&2
  exit 2
fi

targets=(
  "outputs"
  "tmp"
  "tmp 23-11-15-336"
  "test"
  "test全流程"
  "logs"
  ".run"
  ".codex/cinematic-shot-preview"
  ".codex/shot-preview"
  "scripts/tmp"
  "local-backend/tmp"
)
if [[ "$include_build" == "true" ]]; then
  targets+=(
    "cloud-backend/build"
    "local-backend/build"
    "local-backend/dist"
    "frontend/build"
    "frontend/dist"
    "frontend/release"
  )
fi
if [[ ${#custom_targets[@]} -gt 0 ]]; then
  targets=("${custom_targets[@]}")
fi

found="false"
for target in "${targets[@]}"; do
  if [[ -z "$target" || "$target" == /* || "$target" == *".."* ]]; then
    echo "ERROR: archive target must be a safe root-relative path: '$target'" >&2
    exit 2
  fi
  source_path="$workspace_root/$target"
  [[ -e "$source_path" ]] || continue
  found="true"
  size_kib="$(du -sk "$source_path" | awk '{print $1}')"
  archived="payload/$target"
  echo "ARCHIVE $target (${size_kib} KiB)"
  if [[ "$dry_run" == "false" ]]; then
    if [[ ! -e "$snapshot" ]]; then
      mkdir -p "$snapshot/payload"
      printf 'source\tarchived\tsize_kib\n' > "$manifest"
    fi
    destination="$snapshot/$archived"
    mkdir -p "$(dirname "$destination")"
    mv "$source_path" "$destination"
    printf '%s\t%s\t%s\n' "$target" "$archived" "$size_kib" >> "$manifest"
  fi
done

if [[ "$found" == "false" ]]; then
  echo "No generated workspace paths found."
elif [[ "$dry_run" == "false" ]]; then
  echo "Archive created: $snapshot"
fi
